In [24]:
#code 13-1
import numpy as np

def activation(s):
    if s>0 : return 1
    else : return 0

def out(x):
    return activation(W.dot(x))

def train(X,Y,epochs=10):#에폭은 모든 데이터가 다 train process를 들어갔을때. 그 과정을 몇 번 반복할지 정의하는 코드.
    global W, learning_rate
    for t in range(epochs):
        print('epoch =',t,'\n=================================')
        adjusted = 0
        for i in range(len(X)):
            Y_hat = out(X[i])
            error = Y[i]-Y_hat
            if (error !=0) : adjusted +=1
            W += learning_rate*error*X[i]#weight update
            print ('input: ', X[i], 'target: ', Y[i], 'output: ', Y_hat, \
                    'updated weight: ', W, 'error: ',error)
        if adjusted == 0 : return
        
X = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])
Y = np.array([0,0,0,1])
W = np.array([0,0,0],dtype=np.float64)
learning_rate = 0.1
train(X,Y,100)

epoch = 0 
input:  [0 0 1] target:  0 output:  0 updated weight:  [0. 0. 0.] error:  0
input:  [0 1 1] target:  0 output:  0 updated weight:  [0. 0. 0.] error:  0
input:  [1 0 1] target:  0 output:  0 updated weight:  [0. 0. 0.] error:  0
input:  [1 1 1] target:  1 output:  0 updated weight:  [0.1 0.1 0.1] error:  1
epoch = 1 
input:  [0 0 1] target:  0 output:  1 updated weight:  [0.1 0.1 0. ] error:  -1
input:  [0 1 1] target:  0 output:  1 updated weight:  [ 0.1  0.  -0.1] error:  -1
input:  [1 0 1] target:  0 output:  0 updated weight:  [ 0.1  0.  -0.1] error:  0
input:  [1 1 1] target:  1 output:  0 updated weight:  [0.2 0.1 0. ] error:  1
epoch = 2 
input:  [0 0 1] target:  0 output:  0 updated weight:  [0.2 0.1 0. ] error:  0
input:  [0 1 1] target:  0 output:  1 updated weight:  [ 0.2  0.  -0.1] error:  -1
input:  [1 0 1] target:  0 output:  1 updated weight:  [ 0.1  0.  -0.2] error:  -1
input:  [1 1 1] target:  1 output:  0 updated weight:  [ 0.2  0.1 -0.1] error:  1
epoch = 3

In [25]:
def predict(X):
    print ('prediction results')
    print ('x0, x1, y')
    for x in X:
        print('{:2d}{:3d}{:3d}'.format(x[0], x[1], out(x)))

predict(X)

prediction results
x0, x1, y
 0  0  0
 0  1  0
 1  0  0
 1  1  1


In [26]:
from sklearn.linear_model import Perceptron

model = Perceptron(verbose=1)
model.fit(X[:,0:2],Y)

-- Epoch 1
Norm: 0.00, NNZs: 0, Bias: -1.000000, T: 4, Avg. loss: 0.750000
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 1.41, NNZs: 2, Bias: 0.000000, T: 8, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.00, NNZs: 0, Bias: -2.000000, T: 12, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 1.41, NNZs: 2, Bias: -1.000000, T: 16, Avg. loss: 0.500000
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 1.00, NNZs: 1, Bias: -2.000000, T: 20, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 2.24, NNZs: 2, Bias: -1.000000, T: 24, Avg. loss: 0.250000
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 1.00, NNZs: 1, Bias: -3.000000, T: 28, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 2.24, NNZs: 2, Bias: -2.000000, T: 32, Avg. loss: 0.500000
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 1.41, NNZs: 2, Bias: -3.000000, T: 36, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- E

Perceptron(verbose=1)

In [27]:
print(model.coef_)
print(model.intercept_)

[[2. 2.]]
[-2.]


In [29]:
model.predict(X[:,0:2])

array([0, 0, 0, 1])

In [52]:
#code 13-2
from sklearn.neural_network import MLPClassifier
X_xor = X[:,0:2]
Y_xor = ([0,1,1,0])

model_xor = MLPClassifier(hidden_layer_sizes=(3,2),   #hidden layer size = (3,2) 이면 input 2개, 
                                                      #hidden layer에 3개짜리 하나와 , 2개짜리 하나가 생긴다.
                          activation='logistic', #logistic function
                          solver ='lbfgs', #limited-memory BFGS
                          max_iter=100, verbose=1)
model_xor.fit(X_xor,Y_xor)

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =           20     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  7.06083D-01    |proj g|=  7.96747D-02

At iterate    1    f=  6.93224D-01    |proj g|=  1.87951D-03

At iterate    2    f=  6.93214D-01    |proj g|=  5.24064D-04

At iterate    3    f=  6.93203D-01    |proj g|=  1.32890D-03

At iterate    4    f=  6.93169D-01    |proj g|=  2.88028D-03

At iterate    5    f=  6.93032D-01    |proj g|=  7.03962D-03

At iterate    6    f=  6.92872D-01    |proj g|=  9.05882D-03

At iterate    7    f=  6.92702D-01    |proj g|=  6.42586D-03

At iterate    8    f=  6.92570D-01    |proj g|=  1.59499D-03

At iterate    9    f=  6.92532D-01    |proj g|=  2.13261D-03

At iterate   10    f=  6.92481D-01    |proj g|=  4.20416D-03

At iterate   11    f=  6.92360D-01    |proj g|=  7.68469D-03

At iterate   12    f=  6.90732D-01    |proj g|=  4.34370D-02

At iterate   13    f=  6.8

 This problem is unconstrained.


MLPClassifier(activation='logistic', hidden_layer_sizes=(3, 2), max_iter=100,
              solver='lbfgs', verbose=1)


At iterate   53    f=  6.23937D-03    |proj g|=  1.99994D-04

At iterate   54    f=  6.08806D-03    |proj g|=  1.70559D-04

At iterate   55    f=  5.94440D-03    |proj g|=  2.22142D-04

At iterate   56    f=  5.87126D-03    |proj g|=  7.76410D-05

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
   20     56     83      1     0     0   7.764D-05   5.871D-03
  F =   5.8712639294713617E-003

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            


In [53]:
print(model_xor.coefs_)

[array([[ 4.52216369,  4.91471562, -1.36207885],
       [-4.5273651 , -4.13953616, -2.4623474 ]]), array([[ 4.23991839, -6.05545323],
       [-4.71293334,  6.72848285],
       [ 0.34803067, -0.38289926]]), array([[-5.96932663],
       [12.73503556]])]


In [54]:
model_xor.predict(X_xor)

array([0, 1, 1, 0])