In [2]:
import numpy as np
arr = np.arange(1,10)
print(arr)
arr *= 11
print(arr)
arr2 = arr.reshape(3,3)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[11 22 33 44 55 66 77 88 99]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [3]:
print(arr2[0:2,1:3])

[[22 33]
 [55 66]]


In [4]:
print(arr2[:,:-1])
#-1 = 2이다. 따라서 [ :-1] 은 [0,1]을 의미한다.

[[11 22]
 [44 55]
 [77 88]]


In [5]:
img = np.array([[1.,2.],[3.,4.]])

def filter1(img):
    height, width = len(img),len(img[0])
    f_img = np.zeros((width,height))
    for i in range(height):
        f_img[:,(height-1)-i] = img[i,:] #img(rotate(90))의 결과와 같다.
    return f_img
def filter2(img):
    height, width = len(img),len(img[0])
    f_img = np.zeros((width,height))
    for i in range(height):
        f_img[i] = img[i,::-1]
    return f_img


In [6]:
np.max(record["playerA"][record['playerA']<3.0])

NameError: name 'record' is not defined

In [ ]:
record['playerA'][record['playerA']<3.0].max()
#for문 등을 이용해서 장황하게 프로그램을 짜면 컴퓨팅이 오래걸린다.
#따라서 라이브러리를 활용해서 function을 활용해서 처리속도를 줄여야한다.
#파이썬은 되도록 주어진 모듈 안의 함수를 활용해야한다.