In [7]:
import numpy as np
SIZE = 8
print('selected size is ', SIZE)
myArr = np.arange(1,SIZE*SIZE+1,1)
myArr.resize(SIZE,SIZE)
myArr

selected size is  8


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [8]:
myArr[SIZE//2:,SIZE//2:]

array([[37, 38, 39, 40],
       [45, 46, 47, 48],
       [53, 54, 55, 56],
       [61, 62, 63, 64]])

In [13]:
arr1 = np.random.randint(0,255,size = (3,3))
print(arr1)
arr2 = np.random.randint(0,255,size = (3,3))
print(arr2)
condArr = np.random.choice([True,False],size = (3,3))
print(condArr)
np.where(condArr,arr1,arr2)
#where 은 삼항연산자와 같다. 처음 매개변수는 조건문이다.
#만약 조건문이 참이면 두번째 매개변수를 실행하고, 조건문이 거짓이면 세번째 매개변수를 실행한다.
#arr1[condArr]

[[248 126 155]
 [ 39 196 194]
 [125   8 105]]
[[ 39 147  97]
 [179 231  79]
 [120 170 245]]
[[False False  True]
 [False  True False]
 [False  True  True]]


array([155, 196,   8, 105])